### ISSUE TITLE
DrawingBotV3 - Road Map

### ISSUE THREAD

**Issue by SonarSonic** [SonarSonic/DrawingBotV3#29]
**New Features**
- [ ] #28 
- [ ] #24
- [ ] #25 
- [ ] New version of PFM Mosaics which plot the whole image and cut them into the section of the mosaic, making for a more consistent mosaic output.
- [ ] Show path optimization preview / allow choices of faster / more accurate algorithms.
- [ ] New Mosaic which uses comic style shapes
- [ ] Ability to export only geometries within a certain range / geometry culling.

**Improvements**
- [ ] #6 
- [ ] Faster/More efficient Path Optimization
- [ ] Improve handling of progress / progress updates.
- [ ] Add a way background processes.
- [ ] Improve handling of errors.

**Bug Fixes**
- [ ] #18 
- [ ] #14 
- [ ] #13
- [ ] HPGL settings window disappears from "Export Settings" after it has been shown during HPGL export.
